---
title: "Exploring Storms"
author: "arcotdhruva"
execute:
  echo: false
---

```{r}
#| label: setup
#| include: false
suppressPackageStartupMessages(library(tidyverse))
```

## Named Storms per Year

```{r}
#| label: plot-storms
#| message: false
#| warning: false
storms %>%
  filter(status %in% c("tropical depression", "tropical storm", "hurricane")) %>%
  mutate(status = factor(status, levels = c("tropical depression", "tropical storm", "hurricane"))) %>%
  group_by(year, status) %>%
  summarise(n_storms = n_distinct(name)) %>%
  ggplot(aes(x = year, y = n_storms, fill = status)) +
  geom_area() +
  scale_fill_manual(values = c("tropical depression" = "lightblue", 
                               "tropical storm" = "orange", 
                               "hurricane" = "darkred")) +
  labs(title = "Number of Named Storms per Year by Type",
       subtitle = "Filtered to Tropical Depressions, Tropical Storms, and Hurricanes",
       x = "Year",
       y = "Number of Storms",
       fill = "Storm Type") +
  theme_minimal()
```
